TrainingArguments:
    num_train_epochs: 0.3
    per_device_train_batch_size: 1
    per_device_eval_batch_size: 1
    gradient_accumulation_steps=: 1
    warmup_steps: 10
    learning_rate: 5e-5
    logging_steps: 50
    fp16: True
    save_strategy: "no"
    report_to: "none"
    push_to_hub: False 
    dataloader_num_workers: 0

                
    